SET SCOREBOARD OFF
SET DATE FRENCH
SET CONFIRM ON
CLEAR
SET COLOR TO BG+/N
@8,10 TO 16,69 DOUBLE
SET COLOR TO B+/N
@10,20 TO 14,59
SET CURSOR OFF
SET COLOR TO *R+/N
@12,26 SAY 'ESTO ES UNA PIJA'
INKEY(0)
SET COLOR TO
CLEAR
QUIT

