SET SCOREBOARD OFF
SET DATE FRENCH
SET CONFIRM ON
CLEAR
SET COLOR TO BG+/N
@8,5 TO 16,74 DOUBLE
SET COLOR TO B+/N
@10,7 TO 14,72
SET CURSOR ON
SET COLOR TO W+/N,B/W
STORE SPACE(30) TO VNOMBRE
@12,12 SAY 'INGRESE AQUI SU NOMBRE:' GET VNOMBRE PICTURE '@!'
READ
SET CURSOR OFF
CLEAR
SET COLOR TO G+/N
@9,5 TO 15,74
SET COLOR TO W+/N
@11,26 SAY 'EL NOMBRE DEL OPERADOR ES:'
SET COLOR TO *RG+/N
CC=LEN(ALLTRIM(VNOMBRE))/2
@13,69-CC SAY ALLTRIM(VNOMBRE)
SET COLOR TO
@24,22 SAY 'PRESIONE CULQUIER TECLA PARA CONTINUAR'
INKEY(0)
CLEAR
QUIT
